---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - o2ims.oran
  resources:
  - o2calls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - o2ims.oran
  resources:
  - o2calls/finalizers
  verbs:
  - update
- apiGroups:
  - o2ims.oran
  resources:
  - o2calls/status
  verbs:
  - get
  - patch
  - update
